### ISSUE TITLE
Email word-editor type is not always true 

### ISSUE THREAD

**Issue by FedericoGnesotto** [MailMind/OutlookPlugin#3]
Currently we use the word editor for an email to get the selection. For some reason this works only sometimes, in particular it seems to not work the first time a new email is open, but from the second time onwards. We apparently need this word editor mode as default to get the selection and insert text at the selection's position.

**Comment by MahmoudH96** [comment]
Do we still need this as I think we are going to use the dialog to get the bullet point list

**Comment by FedericoGnesotto** [comment]
I don't think so, let's close it for now.
